In [18]:
import xarray as xr
import numpy as np

In [3]:
fpath = '/work/Katherine.Turner/smaller_projects/hifreq-variability/data'

In [34]:
mod = 'ESM4'

ds_storms = xr.open_dataset(f"{fpath}/{mod}_monthly_storms.nc", use_cftime=True)
ds_SAM_djf = xr.open_dataset(f"{fpath}/{mod}_DJF_pc1.nc", use_cftime=True)
ds_SAM_jja = xr.open_dataset(f"{fpath}/{mod}_JJA_pc1.nc", use_cftime=True)
ds_NINO = xr.open_dataset(f"{fpath}/{mod}_nino34.nc", use_cftime=True)

In [35]:
djf_storms = ds_storms.center_counts.resample(time='QS-DEC').sum()[4:-4:4]
djf_SAM = ds_SAM_djf.pcs[1:-1,0]
djf_nino = ds_NINO.nino34.resample(time='QS-DEC').mean()[4:-4:4]

In [36]:
np.corrcoef(djf_storms, djf_SAM), np.corrcoef(djf_storms, djf_nino), np.corrcoef(djf_nino, djf_SAM)

(array([[ 1.        , -0.26797075],
        [-0.26797075,  1.        ]]),
 array([[1.        , 0.10594664],
        [0.10594664, 1.        ]]),
 array([[ 1.        , -0.02185223],
        [-0.02185223,  1.        ]]))

In [37]:
jja_storms = ds_storms.center_counts.resample(time='QS-DEC').sum()[2::4]
jja_SAM = ds_SAM_jja.pcs[:,0]
jja_nino = ds_NINO.nino34.resample(time='QS-DEC').mean()[2::4]

In [38]:
np.corrcoef(jja_storms, jja_SAM), np.corrcoef(jja_storms, jja_nino), np.corrcoef(jja_nino, jja_SAM)

(array([[ 1.        , -0.24273115],
        [-0.24273115,  1.        ]]),
 array([[1.        , 0.01536312],
        [0.01536312, 1.        ]]),
 array([[1.       , 0.1681654],
        [0.1681654, 1.       ]]))